p8105_hw2_gw2442
================
Gwyneth Wei

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.0      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
library(readxl)
```

## Problem 1

Reading and cleaning data in
`NYC_Transit_Subway_Entrance_And_Exit_Data.csv`:

``` r
transit_df = read_csv(
  'data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv',
  col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c")) %>%
  janitor::clean_names() %>%
  select(line:vending, ada) %>%
  mutate(
    entry = ifelse(entry == "YES", TRUE, FALSE))

skimr::skim(transit_df)
```

|                                                  |            |
|:-------------------------------------------------|:-----------|
| Name                                             | transit_df |
| Number of rows                                   | 1868       |
| Number of columns                                | 20         |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |            |
| Column type frequency:                           |            |
| character                                        | 16         |
| logical                                          | 2          |
| numeric                                          | 2          |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |            |
| Group variables                                  | None       |

Data summary

**Variable type: character**

| skim_variable | n_missing | complete_rate | min | max | empty | n_unique | whitespace |
|:--------------|----------:|--------------:|----:|----:|------:|---------:|-----------:|
| line          |         0 |          1.00 |   5 |  17 |     0 |       36 |          0 |
| station_name  |         0 |          1.00 |   4 |  39 |     0 |      356 |          0 |
| route1        |         0 |          1.00 |   1 |   2 |     0 |       24 |          0 |
| route2        |       848 |          0.55 |   1 |   2 |     0 |       20 |          0 |
| route3        |      1374 |          0.26 |   1 |   2 |     0 |       18 |          0 |
| route4        |      1547 |          0.17 |   1 |   1 |     0 |       13 |          0 |
| route5        |      1630 |          0.13 |   1 |   1 |     0 |       12 |          0 |
| route6        |      1741 |          0.07 |   1 |   1 |     0 |        7 |          0 |
| route7        |      1788 |          0.04 |   1 |   2 |     0 |        7 |          0 |
| route8        |      1820 |          0.03 |   1 |   1 |     0 |        3 |          0 |
| route9        |      1840 |          0.01 |   1 |   1 |     0 |        2 |          0 |
| route10       |      1845 |          0.01 |   1 |   1 |     0 |        1 |          0 |
| route11       |      1845 |          0.01 |   1 |   1 |     0 |        1 |          0 |
| entrance_type |         0 |          1.00 |   4 |   9 |     0 |        7 |          0 |
| exit_only     |      1812 |          0.03 |   3 |   3 |     0 |        1 |          0 |
| vending       |         0 |          1.00 |   2 |   3 |     0 |        2 |          0 |

**Variable type: logical**

| skim_variable | n_missing | complete_rate | mean | count               |
|:--------------|----------:|--------------:|-----:|:--------------------|
| entry         |         0 |             1 | 0.94 | TRU: 1753, FAL: 115 |
| ada           |         0 |             1 | 0.25 | FAL: 1400, TRU: 468 |

**Variable type: numeric**

| skim_variable     | n_missing | complete_rate |   mean |   sd |     p0 |    p25 |    p50 |    p75 |   p100 | hist  |
|:------------------|----------:|--------------:|-------:|-----:|-------:|-------:|-------:|-------:|-------:|:------|
| station_latitude  |         0 |             1 |  40.73 | 0.07 |  40.58 |  40.69 |  40.73 |  40.77 |  40.90 | ▂▅▇▃▂ |
| station_longitude |         0 |             1 | -73.94 | 0.06 | -74.03 | -73.99 | -73.96 | -73.91 | -73.76 | ▇▆▃▂▁ |

The dataset `transit_df` contains variables line, station_name, route1 -
route11, entrance_type, vending, entry, exit_only, ada,
station_latitude, and station_longitude.

Following the import of the csv data, a new dataset was created called
`transit_df` where the column names were cleaned using
`janitor::clean_names()`. The variables route8 - route11 were converted
to character variables. The variables of interest were selected from the
original csv file for the new dataset and the variable `entry` was
converted to a logical variable using `ifelse`. The dimensions of the
resulting dataset are 1868 rows and 20 columns. The data is not tidy, as
the columns route1 - route11 are values rather than variable names.

*How many distinct stations are there?*

``` r
select(transit_df, station_name, line) %>%
distinct
```

    ## # A tibble: 465 × 2
    ##    station_name             line    
    ##    <chr>                    <chr>   
    ##  1 25th St                  4 Avenue
    ##  2 36th St                  4 Avenue
    ##  3 45th St                  4 Avenue
    ##  4 53rd St                  4 Avenue
    ##  5 59th St                  4 Avenue
    ##  6 77th St                  4 Avenue
    ##  7 86th St                  4 Avenue
    ##  8 95th St                  4 Avenue
    ##  9 9th St                   4 Avenue
    ## 10 Atlantic Av-Barclays Ctr 4 Avenue
    ## # … with 455 more rows

There are 465 distinct stations.

*How many stations are ADA compliant?*

``` r
transit_df %>%
    filter(ada == TRUE) %>%
    select(station_name, line) %>%
    distinct
```

    ## # A tibble: 84 × 2
    ##    station_name                   line           
    ##    <chr>                          <chr>          
    ##  1 Atlantic Av-Barclays Ctr       4 Avenue       
    ##  2 DeKalb Av                      4 Avenue       
    ##  3 Pacific St                     4 Avenue       
    ##  4 Grand Central                  42nd St Shuttle
    ##  5 34th St                        6 Avenue       
    ##  6 47-50th Sts Rockefeller Center 6 Avenue       
    ##  7 Church Av                      6 Avenue       
    ##  8 21st St                        63rd Street    
    ##  9 Lexington Av                   63rd Street    
    ## 10 Roosevelt Island               63rd Street    
    ## # … with 74 more rows

There are 84 stations that are ADA compliant.

*What proportion of station entrances/exits without vending allow
entrance?*

``` r
transit_df %>%
    filter(vending == "NO") %>%
    pull(entry) %>%
    mean
```

    ## [1] 0.3770492

37.70% of all station entrances/exits without vending allow entrance.

*How many distinct stations serve the A train? Of the stations that
serve the A train, how many are ADA compliant?*

``` r
transit_df %>%
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    values_to = "route_name") %>%
  filter(route_name == "A") %>%
  select (station_name, line) %>%
  distinct
```

    ## # A tibble: 60 × 2
    ##    station_name                  line           
    ##    <chr>                         <chr>          
    ##  1 Times Square                  42nd St Shuttle
    ##  2 125th St                      8 Avenue       
    ##  3 145th St                      8 Avenue       
    ##  4 14th St                       8 Avenue       
    ##  5 168th St - Washington Heights 8 Avenue       
    ##  6 175th St                      8 Avenue       
    ##  7 181st St                      8 Avenue       
    ##  8 190th St                      8 Avenue       
    ##  9 34th St                       8 Avenue       
    ## 10 42nd St                       8 Avenue       
    ## # … with 50 more rows

``` r
transit_df %>%
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    values_to = "route_name") %>%
  filter(route_name == "A", ada == TRUE) %>%
  select(station_name, line) %>%
  distinct
```

    ## # A tibble: 17 × 2
    ##    station_name                  line            
    ##    <chr>                         <chr>           
    ##  1 14th St                       8 Avenue        
    ##  2 168th St - Washington Heights 8 Avenue        
    ##  3 175th St                      8 Avenue        
    ##  4 34th St                       8 Avenue        
    ##  5 42nd St                       8 Avenue        
    ##  6 59th St                       8 Avenue        
    ##  7 Inwood - 207th St             8 Avenue        
    ##  8 West 4th St                   8 Avenue        
    ##  9 World Trade Center            8 Avenue        
    ## 10 Times Square-42nd St          Broadway        
    ## 11 59th St-Columbus Circle       Broadway-7th Ave
    ## 12 Times Square                  Broadway-7th Ave
    ## 13 8th Av                        Canarsie        
    ## 14 Franklin Av                   Franklin        
    ## 15 Euclid Av                     Fulton          
    ## 16 Franklin Av                   Fulton          
    ## 17 Howard Beach                  Rockaway

There are 60 distinct stations that serve the A train. Of the stations
that serve the A train, there are 17 that are ADA compliant.

## Problem 2

Reading and cleaning Mr. Trash Wheel sheet:

-   Variable `trash_wheel` was added for combining the datasets later on

``` r
m_trash_wheel = readxl::read_excel(
  "data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", 
  sheet = "Mr. Trash Wheel",
  range = "A2:N533") %>%
  janitor::clean_names() %>%
  drop_na(dumpster) %>%
  mutate(
    sports_balls = round(sports_balls),
    trash_wheel = "mr") %>%
  select(trash_wheel, everything())
```

Reading and cleaning Professor Trash Wheel sheet:

-   Variable `trash_wheel` was added for combining the datasets later on

``` r
p_trash_wheel = readxl::read_excel(
  "data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx",
  sheet = "Professor Trash Wheel",
  range = "A2:N117") %>%
  janitor::clean_names() %>%
  drop_na(dumpster) %>%
  mutate(
    sports_balls = round(sports_balls),
    trash_wheel = "professor") %>%
  select(trash_wheel, everything())
```

Combining datasets `m_trash_wheel` and `p_trash_wheel`

``` r
trash_wheel_tidy = bind_rows(m_trash_wheel, p_trash_wheel)

skimr::skim(trash_wheel_tidy)
```

|                                                  |                  |
|:-------------------------------------------------|:-----------------|
| Name                                             | trash_wheel_tidy |
| Number of rows                                   | 524              |
| Number of columns                                | 15               |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |                  |
| Column type frequency:                           |                  |
| character                                        | 2                |
| numeric                                          | 12               |
| POSIXct                                          | 1                |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |                  |
| Group variables                                  | None             |

Data summary

**Variable type: character**

| skim_variable | n_missing | complete_rate | min | max | empty | n_unique | whitespace |
|:--------------|----------:|--------------:|----:|----:|------:|---------:|-----------:|
| trash_wheel   |         0 |             1 |   2 |   9 |     0 |        2 |          0 |
| month         |         0 |             1 |   3 |   9 |     0 |       13 |          0 |

**Variable type: numeric**

| skim_variable      | n_missing | complete_rate |     mean |       sd |      p0 |     p25 |      p50 |      p75 |      p100 | hist  |
|:-------------------|----------:|--------------:|---------:|---------:|--------:|--------:|---------:|---------:|----------:|:------|
| dumpster           |         0 |             1 |   201.12 |   138.38 |    1.00 |   66.00 |   191.50 |   322.25 |    453.00 | ▇▅▅▅▅ |
| year               |         0 |             1 |  2017.41 |     1.90 | 2014.00 | 2016.00 |  2018.00 |  2019.00 |   2021.00 | ▅▂▇▃▃ |
| weight_tons        |         0 |             1 |     3.03 |     0.84 |    0.61 |    2.47 |     3.09 |     3.57 |      5.62 | ▁▅▇▃▁ |
| volume_cubic_yards |         0 |             1 |    15.30 |     1.54 |    6.00 |   15.00 |    15.00 |    15.00 |     20.00 | ▁▁▁▇▂ |
| plastic_bottles    |         0 |             1 |  2415.96 |  1890.61 |  210.00 | 1075.00 |  1980.00 |  2875.00 |   9830.00 | ▇▅▁▁▁ |
| polystyrene        |         0 |             1 |  2460.14 |  2016.30 |  210.00 |  990.00 |  2000.00 |  3152.50 |  11528.00 | ▇▃▁▁▁ |
| cigarette_butts    |         0 |             1 | 23118.70 | 30100.16 |  980.00 | 5500.00 | 11000.00 | 28000.00 | 310000.00 | ▇▁▁▁▁ |
| glass_bottles      |         0 |             1 |    21.02 |    16.89 |    0.00 |    8.00 |    18.00 |    29.50 |    110.00 | ▇▃▁▁▁ |
| grocery_bags       |         0 |             1 |  1394.08 |  1748.94 |   50.00 |  480.00 |   890.00 |  1752.50 |  13450.00 | ▇▁▁▁▁ |
| chip_bags          |         0 |             1 |  2584.04 |  3231.04 |  180.00 |  878.50 |  1565.00 |  2760.00 |  20100.00 | ▇▁▁▁▁ |
| sports_balls       |         0 |             1 |    10.18 |     9.42 |    0.00 |    3.00 |     8.00 |    14.00 |     56.00 | ▇▃▁▁▁ |
| homes_powered      |         0 |             1 |    43.49 |    21.06 |    0.00 |   33.62 |    48.83 |    57.17 |     93.67 | ▃▃▇▅▁ |

**Variable type: POSIXct**

| skim_variable | n_missing | complete_rate | min        | max        | median     | n_unique |
|:--------------|----------:|--------------:|:-----------|:-----------|:-----------|---------:|
| date          |         0 |             1 | 1900-01-20 | 2021-01-04 | 2018-04-16 |      298 |

The dataset `trash_wheel_tidy` has 524 observations (453 from dataset
`m_trash_tidy` and 71 from `p_trash_tidy`). There are 15 variables,
including the variable `trash_wheel` that was added to keep track of
which Trash Wheel (Mr. or Professor) is which. Some of the key variables
in this dataset include `dumpster`, `weight_tons`, `volume_cubic_yards`,
and `sports_balls`.

*What was the total weight of trash collected by Professor Trash Wheel?
What was the total number of sports balls collected by Mr. Trash Wheel
in 2020?*

``` r
aggregate (x = trash_wheel_tidy$weight_tons,
           by = list(trash_wheel_tidy$trash_wheel),
           FUN = sum)
```

    ##     Group.1      x
    ## 1        mr 1449.7
    ## 2 professor  135.5

``` r
aggregate (x = trash_wheel_tidy$sports_balls,
           by = list(trash_wheel_tidy$trash_wheel, trash_wheel_tidy$year),
           FUN = sum)
```

    ##      Group.1 Group.2    x
    ## 1         mr    2014  266
    ## 2         mr    2015 1238
    ## 3         mr    2016 1309
    ## 4         mr    2017  530
    ## 5  professor    2017   14
    ## 6         mr    2018  448
    ## 7  professor    2018    0
    ## 8         mr    2019  662
    ## 9  professor    2019    0
    ## 10        mr    2020  856
    ## 11 professor    2020    0
    ## 12        mr    2021   12
    ## 13 professor    2021    0

The total weight of trash collected by Professor Trash Wheel is 135.5
tons. The total number of sports balls collected by Mr. Trash Wheel in
2020 was 856 sports balls.

## Problem 3

Cleaning data in `pols-month.csv`

``` r
pols_df = read_csv("data/fivethirtyeight_datasets/pols-month.csv") %>%
  janitor::clean_names() %>%
  separate(mon, c('year', 'month', 'day'), sep = "-") %>%
  mutate( 
    month = recode(month,
    "01" = "jan", "02" = "feb", "03" = "mar", "04" = "apr", "05" = "may", "06" = "jun", "07" = "jul", "08" = "aug", "09" = "sep", "10" = "oct", "11" = "nov", "12" = "dec"),
    prez_dem = recode(prez_dem, "1" = "dem"),
    prez_gop = recode(prez_gop, "1" = "gop")) %>%
   pivot_longer(
     cols = starts_with("prez"),
     names_to = "temp",
     values_to = "president") %>%
  drop_na("president") %>%
  select(-temp, -day)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    ## Warning: Unreplaced values treated as NA as `.x` is not compatible.
    ## Unreplaced values treated as NA as `.x` is not compatible.
    ## Please specify replacements exhaustively or supply `.default`.

Cleaning data in `snp.csv`

``` r
snp_df = read_csv("data/fivethirtyeight_datasets/snp.csv") %>%
  janitor::clean_names() %>%
  mutate(
    date = as.Date(date, "%m/%d/%y"),
    date = as.Date(ifelse(date > "2015-07-01", format(date, "19%y-%m-%d"), format(date)))) %>%
  separate(date, c('year', 'month', 'day'), sep = "-") %>%
  select(year, month, day, everything()) %>%
  arrange(year, month) %>%
  select(-day) %>%
  mutate(
    month = recode(month,
    "01" = "jan", "02" = "feb", "03" = "mar", "04" = "apr", "05" = "may", "06" = "jun", "07" = "jul", "08" = "aug", "09" = "sep", "10" = "oct", "11" = "nov", "12" = "dec"))
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Cleaning data in `unemployment.csv`

-   Variable `year` was converted to a character variable for combining
    datasets later on

``` r
unemployment_df = read_csv("data/fivethirtyeight_datasets/unemployment.csv") %>%
  janitor::clean_names() %>%
  pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "pct_unemployment") 
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
unemployment_df$year <- as.character(unemployment_df$year)
```

Joining `snp_df` into `pols_df`, and merging`unemployment_df` with the
result

``` r
pols_snp_combined =
  left_join(pols_df, snp_df, by = c("year", "month"))
view(pols_snp_combined)

problem3_tidy = 
  left_join(pols_snp_combined, unemployment_df, by = c("year", "month"))
view(problem3_tidy)

skimr::skim(problem3_tidy)
```

|                                                  |               |
|:-------------------------------------------------|:--------------|
| Name                                             | problem3_tidy |
| Number of rows                                   | 817           |
| Number of columns                                | 11            |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |               |
| Column type frequency:                           |               |
| character                                        | 3             |
| numeric                                          | 8             |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |               |
| Group variables                                  | None          |

Data summary

**Variable type: character**

| skim_variable | n_missing | complete_rate | min | max | empty | n_unique | whitespace |
|:--------------|----------:|--------------:|----:|----:|------:|---------:|-----------:|
| year          |         0 |             1 |   4 |   4 |     0 |       69 |          0 |
| month         |         0 |             1 |   3 |   3 |     0 |       12 |          0 |
| president     |         0 |             1 |   3 |   3 |     0 |        2 |          0 |

**Variable type: numeric**

| skim_variable    | n_missing | complete_rate |   mean |     sd |     p0 |   p25 |    p50 |    p75 |    p100 | hist  |
|:-----------------|----------:|--------------:|-------:|-------:|-------:|------:|-------:|-------:|--------:|:------|
| gov_gop          |         0 |          1.00 |  22.50 |   5.69 |  12.00 |  18.0 |  22.00 |  28.00 |   34.00 | ▆▆▇▅▅ |
| sen_gop          |         0 |          1.00 |  46.10 |   6.40 |  32.00 |  42.0 |  46.00 |  51.00 |   56.00 | ▃▃▇▇▇ |
| rep_gop          |         0 |          1.00 | 194.92 |  29.33 | 141.00 | 176.0 | 195.00 | 222.00 |  253.00 | ▃▇▆▃▅ |
| gov_dem          |         0 |          1.00 |  27.16 |   5.93 |  17.00 |  22.0 |  28.00 |  32.00 |   41.00 | ▆▅▇▆▂ |
| sen_dem          |         0 |          1.00 |  54.38 |   7.38 |  44.00 |  48.0 |  53.00 |  58.00 |   71.00 | ▇▆▇▃▂ |
| rep_dem          |         0 |          1.00 | 244.94 |  31.46 | 188.00 | 211.0 | 250.00 | 268.00 |  301.00 | ▇▂▆▇▅ |
| close            |        36 |          0.96 | 475.43 | 544.07 |  17.05 |  84.3 | 140.64 | 947.28 | 2107.39 | ▇▁▂▁▁ |
| pct_unemployment |        12 |          0.99 |   5.83 |   1.65 |   2.50 |   4.6 |   5.60 |   6.90 |   10.80 | ▃▇▅▂▁ |

After cleaning the `pols-month.csv`, the `pols_df` dataset contained 817
rows and 9 columns. The variables within the dataset included year,
month, president, gov_gop, sen_gop, rep_gop, gov_dem, sen_dem, and
rep_dem. The variable year ranged from 1947-2015.

After cleaning the `snp.csv`, the `snp_df` dataset contained 787 rows
and 3 columns. The variables within the dataset included year, month,
and close. The variable year ranged from 1950-2015.

After cleaning the `unemployment.csv`, the `unemployment_df` dataset
contained 816 rows and 3 columns. The variables within the dataset
included year, month, and pct_unemployment. The variable year ranged
from 1948-1950.

After joining the three datasets into `problem3_tidy`, the resulting
datset contained 817 rows and 11 columns. The variables within the
dataset included year, month, president, gov_gop, sen_gop, rep_gop,
gov_dem, sen_dem, rep_dem, close, and pct_unemployment. The variable
year ranged from 1947-2015.
